using System.Collections.Generic;

namespace FFMQLib
{
	public partial class Patcher
	{
		private static Dictionary<int, PatchInstruction> bank0finstructions = new()
		{
			{ 0x0573, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x0585, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x0B68, new PatchInstruction() { Action = PatchAction.Insert, Chunk = new byte[] { 0xF2 } } },
			{ 0x0B6B, new PatchInstruction() { Action = PatchAction.IncreaseRange, Value = 0x01, Step = 2, Qty = 9 } },
			{ 0x0C3C, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x0C4A, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x0CDC, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x0DC5, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x0DDA, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x0E2A, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x0F67, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x0FC2, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x0FE3, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1082, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1157, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x131F, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1323, new PatchInstruction() { Action = PatchAction.IncreaseRange, Value = 0x01, Step = 2, Qty = 9 } },
			{ 0x143F, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x14F1, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x15F4, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x16AE, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x17B4, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x18B7, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x197E, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1B72, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1B76, new PatchInstruction() { Action = PatchAction.IncreaseRange, Value = 0x01, Step = 2, Qty = 9 } },
			{ 0x1BDA, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1C2D, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1C66, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1CB4, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1CEF, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1D4C, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1DC8, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1E09, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1E0D, new PatchInstruction() { Action = PatchAction.IncreaseRange, Value = 0x01, Step = 2, Qty = 9 } },
			{ 0x1E42, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1E5E, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1E7A, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1EC3, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1EF3, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1F60, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1F72, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1F86, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x1F8A, new PatchInstruction() { Action = PatchAction.IncreaseRange, Value = 0x01, Step = 2, Qty = 9 } },
			{ 0x1FFE, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x204D, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x20AD, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x210E, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x21A6, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x21D3, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2246, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2299, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x229D, new PatchInstruction() { Action = PatchAction.IncreaseRange, Value = 0x01, Step = 2, Qty = 9 } },
			{ 0x262D, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2699, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x26AC, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x26F4, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x273F, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2782, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x280A, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x284D, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2851, new PatchInstruction() { Action = PatchAction.IncreaseRange, Value = 0x01, Step = 2, Qty = 9 } },
			{ 0x2891, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2969, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x299F, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2A49, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2B47, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2B97, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2BB8, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2C42, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2C76, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2D13, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2D60, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2E4D, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2E51, new PatchInstruction() { Action = PatchAction.IncreaseRange, Value = 0x01, Step = 2, Qty = 9 } },
			{ 0x2ED7, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2EEE, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2F92, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x2FEE, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x3002, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x3071, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x30AE, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x3100, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x3171, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x320A, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x320C, new PatchInstruction() { Action = PatchAction.DecreaseWord, Value = 0x01 } },
			{ 0x320E, new PatchInstruction() { Action = PatchAction.IncreaseRange, Value = 0x01, Step = 2, Qty = 5 } },
			{ 0x325E, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x32EE, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x3310, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x336C, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
			{ 0x344E, new PatchInstruction() { Action = PatchAction.Offset, Value = 0x01 } },
			{ 0x344F, new PatchInstruction() { Action = PatchAction.IncreaseWord, Value = 0x01 } },
		};
	}
}
